# crie um pipeline para uma aplicação .net 6 em github actions apenas de ci e com upload de artefatos
name: .NET 6 CI Pipeline        
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Use a versão mais recente do .NET 6 disponível    
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./output
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: ./output

# inclua o job de deployment
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: desenvolvimento
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output


            

